---
title: "SDS 192 Group Contract"
author:
 - Author One
 - Author Two
 - Author Three
date: "Last updated on `r Sys.Date()`"
output: html_document
---

Working in groups can be both incredibly rewarding and incredibly challenging. The most effective collaborations explicitly outline group roles, expectations, and procedures in advance to coordinate how the group will operate, to establish mechanisms of accountability, and to mitigate the risk of conflict. It is important that, throughout the semester, you address group concerns as they come up. This may involve assigning someone to check in with team members that are falling behind, establishing expectations for attending office hours and asking for help, calling team meetings to discuss issues, or reaching out to the instructor to resolve enduring and unresolved conflicts.		

# ROLES

## Who will be responsible for scheduling meetings and hosting Zoom calls? 

FILL ME

## Who will be responsible for facilitating discussion during team meetings?

FILL ME 

## Who will be responsible for taking notes and recording decisions during meetings?

FILL ME

## Who will be responsible for emailing the professor with questions?

FILL ME

## Who will be responsible for requesting group assignment extensions?

FILL ME

## Who will be responsible for setting deadlines for drafts? 

FILL ME

## Who will be responsible for checking in with team members when drafts are late?

FILL ME

## Who will be responsible for reviewing all materials before submission?

FILL ME

## Who will be responsible for submitting assignments?

FILL ME


# COLLABORATIVE WORKSPACES

## Where will the team keep meeting notes? 

FILL ME

## Where will the team store drafts of assignments? 

FILL ME

## Through what channels will the team communicate when not meeting?

FILL ME

## What is the expected response time for emails and messages? 

FILL ME


# MEETINGS

## How often will the team meet? 

FILL ME

## What days/times will the team meet?

FILL ME

## How long will meetings be?

FILL ME

## How will you make decisions during meetings (e.g. consensus, a vote)?

FILL ME
		
## What strategies will you use to stay on task during meetings?

FILL ME

## How should team members inform each other if they are going to be late to a meeting?

FILL ME
			
## When is it ok for a team member to skip a meeting? How soon should they inform the group?

FILL ME

## What will you do if a group member is chronically absent from or late to meetings?

FILL ME

## What will you do if a group member is consistently not participating in meetings?

FILL ME

## What are your expectations for respectful engagement and communication during meetings and in collaborative workspaces? What will you do if a member of your team does not meet these expectations?

FILL ME


# ASSIGNMENTS

## How will you ensure that all team members fully understand assignment expectations? What will you do if your team is unsure how to complete an assignment?

FILL ME

## How will you ensure that all team members are contributing equitably to assignments?

FILL ME

## How soon in advance of deadlines do you expect all team members to share drafts of their work?

FILL ME

## What will be your process for reviewing each other’s work before submission?

FILL ME

## What will you do if the quality of a team member’s work does not meet the group’s expectations? When is it permissible to revise another team member’s work?

FILL ME

## What are your expectations around punctuality regarding group deadlines? How should team members inform each other if they need an extension?

FILL ME

## What will you do if a student is consistently late in submitting draft work?

FILL ME

## What will you do if you discover that a team member’s work violates the Academic Code of Conduct?

FILL ME

# SIGNATURES

* I participated in drafting the standards, roles, and procedures outlined in this document.
* I agree to abide by the terms and conditions outlined in this document.			
* I understand that failing to abide by the terms and conditions outlined in this document may impact my grade.
 							
Signature: FILL ME 
Date: `r format(Sys.time(), '%d %B, %Y')`

Signature: FILL ME 
Date: `r format(Sys.time(), '%d %B, %Y')`

Signature: FILL ME
Date `r format(Sys.time(), '%d %B, %Y')`


Once you are done, in the Git tab in your Environment pane, stage and commit your changes, and then push them to your GitHub repo.  

