---
title: "SDS 192 Mini-Project 1"
subtitle: "SDS 192"
author: 
- name: Author One
  affiliation: Smith College
- name: Author Two
  affiliation: Smith College
- name: Author Three
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
editor: 
  mode: source
output: 
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
library(tidyverse)
library(rscorecard)

sc_key("FILL API KEY HERE")
```

```{r import}
scorecard <- sc_init() %>%
  sc_year(2018) %>%                 #Note how we are looking at only 2018 data here!
  sc_filter(stabbr == "MA") %>%     #Note how we are looking at only Massachusetts data here!
  sc_select(unitid, instnm) %>%
  sc_get()
```

```{r recode}
# Enter your code to recode your variable here. 
```

# Plot 1

```{r plot_1}
# Create plot 1 here
```

# Plot 2

```{r plot_2}
# Create plot 2 here
```

# Blog post

Compose your blog post here...



